#!/usr/bin/env bash

# META:HELP 5:list active local and remote sessions

__pfm-list() {
    if [[ "$1" != "list" ]]
    then
        echo "Must be run as \`pfm list'" >&2
        return 1
    fi
    shift

    local verbose=0
    case "$1" in
        -v|--verbose|verbose|v)
            verbose=1
            shift
            ;;
    esac

    (
        \cd "$PFM_SESSIONS" || return $?
        shopt -s nullglob
        local s
        for s in *
        do
            echo "$s=$(realpath "$s")"
        done \
        | \awk -v verbose="$verbose" -v folder="$PFM_SESSIONS" '
            BEGIN {
                FS="="
                last_ssh_host="dummy"
                last_type="dummy"
            }
            $1 != last_ssh_host || $2 != last_type {
                last_ssh_host=$1
                last_type=$2
                print $1 "[" $2 "]"
            }
            {
                if ($2 == "local") {
                    if ($4 == "localhost" || $4 == "127.0.0.1" || $4 == "::1") {
                        print "- localhost:" $3 " -> " $1 ":" $5
                    } else {
                        print "- localhost:" $3 " -> " $1 " -> " $4 ":" $5
                    }
                } else {
                    if ($4 == "localhost" || $4 == "127.0.0.1" || $4 == "::1") {
                        print "- " $1 ":" $3 " -> localhost:" $5
                    } else {
                        print "- " $1 ":" $3 " -> localhost -> " $4 ":" $5
                    }
                }
                if (verbose) {
                    printf "  link : %s/%s=%s=%s=%s=%s\n", folder, $1, $2, $3, $4, $5
                    printf "  real : %s\n", $6
                }
            }
        '
    )
    return $?
}


:; __pfm-list "$@"
