#!/usr/bin/env bash

__pfm-list__completion() {
  local cur cword
  _get_comp_words_by_ref cur cword
  (
    \cd "$PFM_SESSIONS" || return 1
    if [ "$cword" -gt "2" ]
    then
      compgen -A file -- "$cur"
    else
      compgen -W "-o --obeyform -v --verbose" -A file -- "$cur"
    fi
  )
}

:; __pfm-list__completion
