#!/usr/bin/env bash

__pfm-init() {
    if [[ "$1" != "init" ]]
    then
        echo "Must be run as \`pfm init'" >&2
        return 1
    fi
    shift
    
    if [ -z "$1" ]
    then
        echo "Run the below in your shell and add it your shell rc file"
        # shellcheck disable=SC2016
        echo 'eval "$(pfm init -)"'
        return
    fi
    
    if [ -z "$PFM_EXEC" ]
    then
        echo "pfm exec path unset - make sure you are using \`pfm init'" >&2
        return 2
    fi
    
    echo "export PFM_HOME=\"$PFM_HOME\""
    echo "export PFM_EXEC=\"$PFM_EXEC\""
    echo "export PFM_SESSIONS=\"$PFM_SESSIONS\""
    echo "export PFM_SHELL_INIT=1"
    (
        shopt -s nullglob
        local f
        for f in "$PFM_EXEC"/*
        do
            \grep -Ehv "^\s*(:;|#)" "$f"
        done
    )

    local folder
    for folder in "$PFM_HOME" "$PFM_SESSIONS"
    do
        if ! mkdir -p "$folder"
        then
            echo "Cannot create folder \"$folder\"" >&2
            return 3
        fi
    done
}

# shellcheck disable=SC2016
:; __pfm-init "$@"
