#!/usr/bin/env bash

# META-HELP:10:diagnostics

__pfm-doctor() {
    if [[ "$1" != "doctor" ]]
    then
        echo "Must be run as \`pfm doctor'" >&2
        return 1
    fi
    shift

    if [[ "$1" == "completion" ]]
    then
      return
    fi

    if [[ "1" != "$PFM_SHELL_INIT" ]]
    then
        echo "pfm not initialised in this shell, see \`pfm init'"
    else
        echo "pfm is initialised in this shell :)"
    fi
    (
        shopt -s nullglob
        for f in "$PFM_LIBEXEC"/*
        do
            local basef; basef="$(basename "$f")"
            printf "%-20s : %s\n" "$basef" "$(type -t "$basef")"
        done
    )

    echo
    echo "Environment"
    echo "PFM_HOME     : $PFM_HOME"
    echo "PFM_SESSIONS : $PFM_SESSIONS"
    echo "PFM_BIN      : $PFM_BIN"
    echo "PFM_LIBEXEC  : $PFM_LIBEXEC"
    echo "PFM_SHELL    : $PFM_SHELL"

    echo
    echo "PATH info"
    echo -n "PFM_BIN on path                : "
    if [[ "$PATH" =~ (^|:)"$PFM_BIN"(:|$) ]]
    then
        echo "Yes"
    else
        echo "No"
    fi

    echo -n "PFM_LIBEXEC on path            : "
    if [[ "$PATH" =~ (^|:)"$PFM_LIBEXEC"(:|$) ]]
    then
        echo "Yes"
    else
        echo "No"
    fi

    echo -n "PFM_LIBEXEC is before PFM_BIN  : "
    if [[ "$PATH" =~ (^|:)"$PFM_LIBEXEC":(.*:)?"$PFM_BIN"(:|$) ]]
    then
        echo "Yes"
    else
        echo "No"
    fi

    if [ -n "$PFM_SHELL" ]
    then
        echo
        echo "Shell support"
        pfm init "$PFM_SHELL" | sed -n '/^#/{s/^# *//;p;}'
    fi

    if [ -n "$PFM_SESSIONS" ] && [ -d "$PFM_SESSIONS" ]
    then
        echo
        echo "Sessions"
        __pfm-list list -v
    fi
}

# shellcheck disable=SC2016
:; __pfm-doctor "$@"
