#!/usr/bin/env bash

# META-HELP:5:list active local and remote sessions

__pfm-list() {
    if [[ "$1" != "list" ]]
    then
        echo "Must be run as \`pfm list'" >&2
        return 1
    fi
    shift

    local verbose=0
    local obeyform=0
    while [[ "$1" == -* ]]
    do
      case "$1" in
        -o|--obeyform)
            obeyform=1
            shift
            ;;
        -v|--verbose)
            verbose=1
            shift
            ;;
      esac
    done

    \cd "$PFM_SESSIONS" || return $?
    (
        local last_hosttype
        local first=1
        shopt -s nullglob
        local ignoremarker=${1:+ignore}
        local s
        for s in "$PFM_SESSIONS"/"${ignoremarker}"* "$@"
        do
            if ! [[ "$s" =~ = ]]
            then
              echo "Invalid session file: $s" >&2
              continue
            fi

            read -r state ssh_host ftype from_port to_host to_port s_real desc <<< "$(__pfm-conninfo conninfo "$s")"
            : "$from_port" "$to_host" "$to_port" # ignored
            if [[ "$last_hosttype" != "${ssh_host} [$ftype]" ]]
            then
                last_hosttype="${ssh_host} [$ftype]"
                if [[ "$first" == 1 ]]
                then
                    first=0
                else
                    echo
                fi
                echo "# $last_hosttype"
            fi

            if [[ "$obeyform" == "1" ]]
            then
              if [ "$ftype" == "local" ]
              then
                echo "$ftype $from_port $ssh_host $to_host $to_port"
              else
                echo "$ftype $ssh_host $from_port $to_host $to_port"
              fi
            else
              printf "%-12s : %s\n" "$state" "$desc"
              if [[ "$verbose" == "1" ]]
              then
                echo "             > $s"
                if [[ "$s_real" != "$s" ]]
                then
                  echo "             > $s_real"
                fi
              fi
            fi
        done
    )
    return $?
}


:; __pfm-list "$@"
