#!/usr/bin/env bash

# META-HELP:5:list active local and remote sessions

__pfm-list() {
    if [[ "$1" != "list" ]]
    then
        echo "Must be run as \`pfm list'" >&2
        return 1
    fi
    shift

    local verbose=0
    case "$1" in
        -v|--verbose|verbose|v)
            verbose=1
            shift
            ;;
    esac

    \cd "$PFM_SESSIONS" || return $?
    (
        local last_hosttype
        local first=1
        shopt -s nullglob
        local s
        for s in "$PFM_SESSIONS"/*
        do
            read -r state ssh_host ftype from_port to_host to_port s_real desc <<< "$(__pfm-conninfo conninfo "$s")"
            : "$from_port" "$to_host" "$to_port" # ignored
            if [[ "$last_hosttype" != "${ssh_host} [$ftype]" ]]
            then
                last_hosttype="${ssh_host} [$ftype]"
                if [[ "$first" == 1 ]]
                then
                    first=0
                else
                    echo
                fi
                echo "$last_hosttype"
            fi

            printf "%-12s : %s\n" "$state" "$desc"
            if [[ "$verbose" == "1" ]]
            then
                echo "             > $s"
                if [[ "$s_real" != "$s" ]]
                then
                  echo "             > $s_real"
                fi
            fi
        done
    )
    return $?
}


:; __pfm-list "$@"
