#!/usr/bin/env bash

# META-HELP:2:initialise pfm in the current shell

__pfm-init() {
    if [[ "$1" != "init" ]]
    then
        echo "Must be run as \`pfm init'" >&2
        return 1
    fi
    shift

    if ! [[ "$PFM_SHELL" =~ bash ]]
    then
        echo "pfm init is only supported on bash, don't worry, everything will still work :)" >&2
        return
    fi
    
    if [ -z "$1" ]
    then
        echo "Run the below in your shell and add it your shell rc file"
        # shellcheck disable=SC2016
        echo 'eval "$(pfm init -)"'
        return
    fi
    
    if [ -z "$PFM_LIBEXEC" ]
    then
        echo "pfm exec path unset - make sure you are using \`pfm init'" >&2
        return 2
    fi
    
    echo "export PFM_HOME=\"$PFM_HOME\""
    echo "export PFM_BIN=\"$PFM_BIN\""
    echo "export PFM_LIBEXEC=\"$PFM_LIBEXEC\""
    echo "export PFM_SESSIONS=\"$PFM_SESSIONS\""
    echo "export PFM_SHELL_INIT=1"
    (
        shopt -s nullglob
        local f
        for f in "$PFM_LIBEXEC"/*
        do
            \grep -Ehv "^\s*(:;|#)" "$f"
        done
    )

    local folder
    for folder in "$PFM_HOME" "$PFM_SESSIONS"
    do
        if ! mkdir -p "$folder"
        then
            echo "Cannot create folder \"$folder\"" >&2
            return 3
        fi
    done
}

# shellcheck disable=SC2016
:; __pfm-init "$@"
