#!/usr/bin/env bash

__pfm-list__completion() {
  local cur cword
  _get_comp_words_by_ref cur cword
  (
    \cd "$PFM_SESSIONS" || return 1
    if [[ "$cword" == "2" ]]
    then
      compgen -W "-o --obeyform -v --verbose" -- "$cur"
    fi
    compgen -f -X '!*=*' -- "$cur"
  )
}

:; __pfm-list__completion
