#!/usr/bin/env bash

__pfm-local__completion() {
  local cur cword
  _get_comp_words_by_ref cur cword

  if [[ "$cword" == 3 ]]
  then
    compgen -A hostname -- "$cur"
  fi
}

:; __pfm-local__completion


