#!/usr/bin/env bash

__pfm-local__completion() {
  local cur cword
  _get_comp_words_by_ref cur cword

  if [[ "$cword" == 3 ]]
  then
    compgen -W "
      127.0.0.1
      ::1
      localhost
      $(
        awk '/^Host/ {
          for (i=2; i<=NF; i++) {
            if ($i !~ /\*/) {
              print $i
            }
          }
        }' ~/.ssh/config $(awk '/^Include / { print $2 }' ~/.ssh/config) 2>/dev/null
        sed 's/^\[//;s/\]:[[:digit:]]*//;s/ .*//' ~/.ssh/known_hosts 2>/dev/null
      )
    " -- "$cur"
  fi
}

:; __pfm-local__completion


