#!/usr/bin/env bash

# META-HELP:7:stop a port forwarding session

__pfm-stop() {
    if [[ "$1" != "stop" ]]
    then
        echo "Must be run as \`pfm stop'" >&2
        return 1
    fi
    shift

  if  [[ "$1" == "completion" ]]
  then
    local cur prev cword
    _get_comp_words_by_ref -n '=' cur prev cword
    if [ "$cword" = 2 ]
    then
      local cmd
      for cmd in "-" "all"
      do
        if [ -z "$cur" ] || [[ "$cmd" =~ ^$cur ]]
        then
          printf "%s " "$cmd"
        fi
      done
      return
    fi

    if [ "$cword" = 3 ] && [[ "$prev" == "-" ]]
    then
      (
        \cd "$PFM_SESSIONS" || return 1
        compgen -f -- "$cur"
      )
      return $?
    fi

    return
  fi

    local type=$1
    local session_file

    if  [ -z "$type" ]
    then
        echo "Usage: pfm stop { - <session file> | all }"
        return
    elif [[ "-" == "$type" ]]
    then
        session_file=$2

        if ! [ -S "$session_file" ] && [ -S "$PFM_SESSIONS/$session_file" ]
        then
            session_file="$PFM_SESSIONS/$session_file"
        fi
    elif [[ "all" == "$type" ]]
    then
        session_file="all"
    else
        echo "Invalid stop request" >&2
        return 2
    fi
    # TODO else we construct from inputs - delegate to some other func so we can also use in local etc.

    if [[ "$session_file" == "all" ]]
    then
        (
            local err=0
            shopt -s nullglob
            local f
            for f in "$PFM_SESSIONS"/*
            do
                if [ -S "$f" ] || [ -L "$f" ]
                then
                    __pfm-stop stop - "$f" || err=3
                fi
            done
            return $err
        )
        return $?
    fi

    local session_socket; session_socket="$(realpath "$session_file")"

    if ! [ -e "$session_socket" ] && [ -L "$session_file" ]
    then
        echo -n "Cleaning up disconnected session at $session_file ..."
        if ! rm -f "$session_file" >/dev/null
        then
            echo "Failed to remove session file" >&2
            return 4
        fi
        echo "Done"
        return
    fi

    if ! [ -S "$session_socket" ]
    then
        # TODO we should emit the conn details, might need to destructure session_file
        echo "No port forwarding found for $session_file" >&2
        return 5
    fi

    echo -n "Stopping session at $session_file ..."
    if ! ssh -S "$session_socket" -O exit "" &>/dev/null
    then
        echo "Failed" >&2
        return 6
    fi
    echo "Done"

    if ! rm  -f "$session_file"
    then
        echo "Failed to remove session file" >&2
        return 7
    fi
}

:; __pfm-stop "$@"
