#!/usr/bin/env bash

# META-HELP:7:update pfm to the latest version

__pfm-update() {
    if [[ "$1" != "update" ]]
    then
        echo "Must be run as \`pfm update'" >&2
        return 1
    fi
    shift

    # todo might need to do something smart here to prevent issues with local dev?

    if [ -d "$PFM_HOME/.git" ]
    then
        if ! type -t git &>/dev/null
        then
            echo "pmf is a git repository installation but git not found on system, cannot update" >&2
            return 2
        fi

        git -C "$PFM_HOME" pull || return $?
    # Not distributed through brew so not enabled
    #elif type -t brew &>/dev/null && [[ "$(realpath "$(which pfm)")" =~ ^"$(brew --cellar)"/pfm ]]
    #then
    #    brew upgrade pfm
    #    return $?
    else
        echo "PFM updates are not supported by your installation method :(" >&2
        return 3
    fi

    if [[ "1" == "$PFM_FILE_EXEC" ]]
    then
        if [[ "$(type -t pfm 2>/dev/null)" == "function" ]]
        then
            echo "Run the below to update your shell"
            # shellcheck disable=SC2016
            echo 'eval "$(pfm init -)"'
        fi
        return
    fi

    eval "$(pfm init -)"
}

:; __pfm-update "$@"
