#!/usr/bin/env bash

__pfm-remote__completion() {
  local cur cword
  _get_comp_words_by_ref cur cword

  if [[ "$cword" == 2 ]]
  then
    compgen -A hostname -- "$cur"
  fi
}

:; __pfm-remote__completion


