#!/usr/bin/env bash

# META:HELP 10:diagnostics

__pfm-doctor() {
    if [[ "$1" != "doctor" ]]
    then
        echo "Must be run as \`pfm doctor'" >&2
        return 1
    fi
    shift

    if ! [[ "$(type -t pfm)" == "function" ]]
    then
        echo "pfm not initialised in this shell, see \`pfm init'"
    else
        echo "pfm is initialised in this shell :)"
    fi

    echo
    echo "Environment"
    echo "PFM_EXEC     : $PFM_EXEC"
    echo "PFM_HOME     : $PFM_HOME"
    echo "PFM_SESSIONS : $PFM_SESSIONS"

    if [ -n "$PFM_SESSIONS" ] && [ -d "$PFM_SESSIONS" ]
    then
        (
            local first=1
            shopt -s nullglob
            local s
            for s in "$PFM_SESSIONS"/*
            do
                if [[ "$first" == "1" ]]
                then
                    echo
                    echo "Sessions"
                    first=0
                fi

                local state="Connected   "
                if ! [ -S "$s" ]
                then
                    state="NotSocket   "
                elif ! ssh -S "$s" -O check "" &>/dev/null
                then
                    state="Disconnected"
                fi
                echo "$state : $s"
            done
        )
    fi
}

# shellcheck disable=SC2016
:; __pfm-doctor "$@"
