#!/usr/bin/env bash

# META:HELP 6:forward a local port to a remote host

__pfm-local() {
    if [[ "$1" != "local" ]]
    then
        echo "Must be run as \`pfm local'" >&2
        return 1
    fi
    shift

    local lport=$1
    local ssh_host=$2
    local rhost=$3
    local rport=$4

    if [ -z "$3" ]
    then
        rhost=localhost
        rport=$lport
    elif [ -z "$4" ]
    then
        rhost=localhost
        rport=$3
    fi
    
    if [ -z "$rport" ]
    then
        echo "Usage: pfm local <local port> <ssh host> [remote host [remote port]]" >&2
        return 2
    fi

    local session_file="$PFM_SESSIONS/${ssh_host}=local=${lport}=${rhost}=${rport}"
    local session_socket; session_socket="$PFM_SESSIONS/.l.$(cksum <<< "$session_file" | cut -f 1 -d ' ')"
    if [ -e "$session_file" ] || [ -e "$session_socket" ]
    then
        echo "Session already exists for localhost:$lport -> $ssh_host -> $rhost:$rport" >&2
        return 3
    fi

    if ! ssh -M -S "$session_socket" -fnNT "$ssh_host"
    then
        echo "Failed to establish connection to $ssh_host" >&2
        __pfm-stop stop - "$session_socket" || :
        return 4
    fi

    if ! ssh -S "$session_socket" -O forward -L "$lport:$rhost:$rport" "$ssh_host"
    then
        echo "Failed to forward local port localhost:$lport -> $ssh_host -> $rhost:$rport" >&2
        __pfm-stop stop - "$session_socket" || :
        return 5
    fi

    if ! ln -s "$session_socket" "$session_file"
    then
        echo "Failed to link unix socket for local port localhost:$lport -> $ssh_host -> $rhost:$rport" >&2
        __pfm-stop stop - "$session_socket" || :
        return 6
    fi
}

:; __pfm-local "$@"
