#!/usr/bin/env bash

# META-HELP:1:show this help

__pfm-help() {
    echo "Usage: pfm cmd [option...]"
    echo
    echo "Commands:"
    (
        shopt -s nullglob
        grep "^# *META-HELP" "$PFM_LIBEXEC"/* \
            | sed 's/.*pfm-\(.*\):.*META-HELP *:\(.*\):\(.*\)$/\2 \1 \3/' \
            | sort -n \
            | cut -f 2- -d ' ' \
            | awk '{
                $1 = sprintf(" - %-10s :", $1);
                print;
            }'
    )
    echo
    echo "Environment modifiers"
    echo " PFM_DEBUG           : set to 1 to show traces"
    echo " PFM_CONNECT_TIMEOUT : (default 5) the time, in seconds, to wait for a successful ssh connection"

}

:; __pfm-help "$@"
