#!/usr/bin/env bash

:; export PS4_PADDING="                                "
:; export PS4='+ $(basename ${BASH_SOURCE[0]}):${FUNCNAME[0]}:$LINENO ${PS4_PADDING:0:((${#PS4_PADDING}-${#FUNCNAME[0]}-${#LINENO}-$(basename ${BASH_SOURCE[0]} | wc -c)-1))} '
:; [[ "$PFM_DEBUG" == 1 ]] && set -x

:; export PFM_HOME; PFM_HOME="${PFM_HOME:-$HOME/.pfm}"
:; export PFM_SESSIONS; PFM_SESSIONS="${PFM_SESSIONS:-$PFM_HOME/sessions}"
:; mkdir -p "$PFM_SESSIONS"
:; export PFM_EXEC; PFM_EXEC=$(realpath "$(dirname "$(dirname "$(realpath "$0")")")"/libexec) || { echo "Cannot resolve exec path from \"$0\"" >&2; exit 1; }
:; export PATH="$PFM_EXEC:$PATH"

pfm() {
    (
        if [[ "$PFM_DEBUG" == 1 ]]
        then
            export PS4_PADDING="                                "
            export PS4='+ $(basename ${BASH_SOURCE[0]}):${FUNCNAME[0]}:$LINENO ${PS4_PADDING:0:((${#PS4_PADDING}-${#FUNCNAME[0]}-${#LINENO}-$(basename ${BASH_SOURCE[0]} | wc -c)-1))} '
            set -x
            export PFM_DEBUG
            export SHELLOPTS
        fi
        __pfm_run "$@"
    )
}

__pfm_run() {
    local cmd=${1:-help}
    local full_cmd="__pfm-${cmd}"
    if ! type -t "$full_cmd" &>/dev/null
    then
        echo "Unrecognised command: $cmd" >&2
        return 1
    fi

    "$full_cmd" "$@"
}

:; pfm "$@"
