#!/usr/bin/env bash

pfm-stop() {
    if [[ "$1" != "stop" ]]
    then
        echo "Must be run as \`pfm stop'" >&2
        return 1
    fi
    shift

    local type=$1
    local session_file

    if [[ "-" == "$type" ]]
    then
        session_file=$2

        if ! [ -S "$session_file" ] && [ -S "$PFM_SESSIONS/$session_file" ]
        then
            session_file="$PFM_SESSIONS/$session_file"
        fi
    elif [[ "all" == "$type" ]]
    then
        session_file="all"
    else
        echo "Invalid stop request" >&2
        return 2
    fi
    # TODO else we construct from inputs - delegate to some other func so we can also use in local etc.

    if [[ "$session_file" == "all" ]]
    then
        (
            local err=0
            shopt -s nullglob
            local f
            for f in "$PFM_SESSIONS"/*
            do
                if [ -S "$f" ]
                then
                    pfm-stop stop - "$f" || err=4
                fi
            done
            return $err
        )
        return $?
    fi

    if ! [ -S "$session_file" ]
    then
        # TODO we should emit the conn details, might need to destructure session_file
        echo "No port forwarding found for $session_file" >&2
        return 3
    fi

    echo -n "Stopping session at $session_file..."

    if ! ssh -S "$session_file" -O exit "" &>/dev/null
    then
        echo "Failed" >&2
        return 4
    fi
    echo "Done"

    if ! rm  -f "$session_file"
    then
        echo "Failed to remove session file" >&2
        return 5
    fi
}

:; pfm-stop "$@"
