#!/usr/bin/env bash

pfm-update() {
    if [[ "$1" != "update" ]]
    then
        echo "update must be first arg - make sure you are using \`pfm update'" >&2
        return 1
    fi
    shift

    # todo might need to do something smart here to prevent issues with local dev?

    if [ -d "$PFM_HOME/.git" ]
    then
        if ! type -t git &>/dev/null
        then
            echo "pmf is a git repository installation but git not found on system, cannot update" >&2
            return 2
        fi

        git -C "$PFM_HOME" pull
        return $?
    fi

    # Not distributed through brew so not enabled
    #if type -t brew &>/dev/null && [[ "$(realpath "$(which pfm)")" =~ ^"$(brew --cellar)"/pfm ]]
    #then
    #    brew upgrade pfm
    #    return $?
    #fi
    
    echo "PFM updates are not supported by your installation method :(" >&2
    return 3
}

:; pfm-update "$@"
