#!/usr/bin/env bash

pfm-list() {
    (
        cd "$PFM_SESSIONS" || return $?
        shopt -s nullglob
        local s
        for s in *
        do
            echo "$s"
        done \
        | awk '
            BEGIN {
                FS="="
                last_ssh_host="dummy"
                last_type="dummy"
            }
            $1 != last_ssh_host || $2 != last_type {
                last_ssh_host=$1
                last_type=$2
                print $1 "[" $2 "]"
            }
            {
                if ($2 == "local") {
                    print "- localhost:" $3 " -> " $1 " -> " $4 ":" $5
                } else {
                    print "- " $1 ":" $3 " -> localhost -> " $4 ":" $5
                }
            }
        '
    )
    return $?
}


:; pfm-list "$@"
